### ISSUE TITLE
Autoupdate Slugs/Redirects of subpages (10LTS)

### ISSUE THREAD

**Issue by h3nn3s** [avionbg/save_close_ce#6]
Hi,

v10 brings a feature to automatically update all slugs of subpages and adds redirects if slug of page is changed. This behaviour is not trigged when `save n close` button is clicked.

Would be a nice additional feature for version 10 LTS

Kind regards
Henrik

**Comment by Patta** [comment]
Can not confirm this. The update of subpage slugs is triggered and the redirects are created. The only thing that is missing are the notification after save and close.

**Comment by sypets** [comment]
> The only thing that is missing are the notification after save and close.

The notification for reverting slug / change redirects not only notifies but makes it possible to revert. 

That this is broken if save+close is pressed can be a problem because it is not possible to **revert** the redirect creation. In any case it breaks existing core functionality.
