### ISSUE TITLE
False version number in ext_emconf.php for 1.1.0

### ISSUE THREAD

**Issue by hoermannklaus** [avionbg/save_close_ce#7]
I make a composer update to get the version 1.1.0. Everything works fine, the composer.lock says version "1.1.0" for "goran/save_close_ce". But when I download the dist url zip file under "https://api.github.com/repos/avionbg/save_close_ce/zipball/52f462fdf5970739017dabc89674f465edaf5602" I get an extension where the "ext_emconf.php" still has version "1.0.3" in it. Maybe you could fix this.

Thanks

**Comment by avionbg** [comment]
Fixed
